name: CI

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild BattleShip/BattleShip.sln /t:Restore

    - name: Build solution
      run: msbuild BattleShip/BattleShip.sln /p:Configuration=Release

    - name: Run unit tests
      run: |
        dotnet test BattleShip_Tests/BattleShip_Tests.csproj --configuration Release --no-build --logger trx --results-directory ./TestResults

    - name: Publish code coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./TestResults/**/*.xml
        fail_ci_if_error: true