jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: ./BattleShip
      run: dotnet restore

    - name: Install Windows Desktop workload
      run: dotnet workload install microsoft-net-sdk-windowsdesktop

    - name: Build project
      working-directory: ./BattleShip
      run: dotnet build --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test ./BattleShip_Tests/BattleShip_Tests.csproj \
            --no-build --configuration Release \
            --logger "trx" --results-directory ./TestResults

    - name: Publish code coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./TestResults/**/*.xml
        fail_ci_if_error: true
